import React from 'react';

const EmiOptions = 
        {   
        NoCostEmi: [
            {
                id: 1,
                duration: "3-months EMI",
                amount: "Rs. 20,534",
                per: "per month",
                EMIValue: "64240",
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
            {
                id: 2,
                duration: "6-months EMI",
                amount: "Rs. 10,534",
                per: "per month",
                EMIValue: "64240" ,
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
            {
                id: 3,
                duration: "9-months EMI",
                amount: "Rs. 5,534",
                per: "per month",
                EMIValue: "64240" ,
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
            {
                id: 4,
                duration: "12-months EMI",
                amount: "Rs. 2,534",
                per: "per month",
                EMIValue: "64240" ,
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
        ],
        EmiWithInterest: [
            {
                id: 1,
                duration: "18-months EMI",
                amount: "Rs. 20,534",
                per: "per month",
                rate: "@15% p.a.",
                EMIValue: "64240" ,
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
            {
                id: 2,
                duration: "24-months EMI",
                amount: "Rs. 20,534",
                per: "per month",
                rate: "@15% p.a.",
                EMIValue: "64240" ,
                interest:"64240",
                discount:"64240",
                total: "64240",
                one: "EMIValue",
                two: "Interest charged by bank",
                three: "No cost EMI discount",
                four:"Total amount",
            },
        ]
}


export default EmiOptions